# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wozback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='next_dialog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_behavior', to='wozback.Dialog'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
