# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wozback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='agent name is max 100 characters', max_length=100)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(help_text='agent name is max 100 characters', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(help_text='agent name is max 100 characters', max_length=100)),
                ('action', models.CharField(help_text='agent name is max 100 characters', max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='wozback.Agent')),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Experiment',
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.DeleteModel(
            name='Bubble',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='behavior',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='wozback.Dialog'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='next_dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_behavior', to='wozback.Dialog'),
        ),
        migrations.AddField(
            model_name='agent',
            name='experiments',
            field=models.ManyToManyField(related_name='agents', to='wozback.Experiment'),
        ),
    ]
