# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wozback', '0003_behavior_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='wozback.Agent'),
        ),
    ]
