# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wozback', '0004_dialog_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavior',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experimentresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='user',
        ),
    ]
