# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wozback', '0006_auto_20171202_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='wozback.ExperimentResult')),
            ],
        ),
    ]
