# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wozback', '0009_auto_20171208_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='experiment',
        ),
        migrations.AddField(
            model_name='test',
            name='experiment',
            field=models.ManyToManyField(null=True, related_name='test', to='wozback.Experiment'),
        ),
    ]
