# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wozback', '0010_auto_20171208_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='experiment',
        ),
        migrations.AddField(
            model_name='test',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='wozback.Experiment'),
        ),
    ]
